### ISSUE TITLE
preserve copyright with copying assertpy code

### ISSUE THREAD

**Issue by saturnboy** [ninadmhatre/simple-assertions#5]
I'm happy that you like `assertpy` and that it inspired you to write a derivative assertion library.

Please note that `assertpy` is released under the 3-clause BSD license, and Clause 1 says "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer."  Please include the copyright when directly copying the assertpy codebase which you have done repeatedly.

I'd also say that a link or two to https://assertpy.github.io/ or https://github.com/assertpy/assertpy in your readme would be nice.

**Comment by ninadmhatre** [comment]
Hi @saturnboy, i am not really good with Licences so am i correct here that i just need to add link to original source code in my readme and no change is required in license file already part of this module?

**Comment by saturnboy** [comment]
I appreciate you including a link.

I'm not a lawyer either, but thankfully the BSD license is like 15 lines of plain english.  When you directly copy and paste assertpy code into your library, you are not merely "inspired" by it...just are just copying it (aka you are redistributing my code in your repo).  And that's totally ok, and that's what open source is all about.  But when you do that, because assertpy is BSD licensed, you need to preserve the copyright notice from the top of the assertpy files in the copied code (to tell everyone, that hey I only wrote these parts...but not these other parts).  I'd probably suggest you put all the directly copied parts in one file to keep them separate from the parts you wrote (that will be copyright by you).

**Comment by ninadmhatre** [comment]
Hi @saturnboy, i think with the latest change i copied assertpy license as well. only reason i used word "inspired" because i did not copy everything that you did, that would have been useless as well. if you want i can put trimmed down version of assertpy as well. and most of the assertions are common i.e. there is no other way to write `equals_to` than `a != b`. i am also setting up variable and cleaning it before next assertion is picked so that's my addition, my errors are generated differently (you can call that as a code cleanup) but there are few code parts which i copied due to lack of time to come up with something working, but i will replace them in future with my own implementation. only thing i feel i really copied is word "assert_that" again its common english word but i did not mention that in my keyword list so that if anyone searches for those words it goes to your lib.

my intention was not copy stuff and get the credit if you think so i just want to clear that :), i did it because i wanted something which is really small for my needs and i added it here just in case. i gave all the credit to original library. But i will change the direct copy paste parts with my own implementation and if possible use another keyword for `assert_that`
